import { type Project } from "@/lib/utils";

export const projects: Project[] = [
  {
    project_id: "hematyu",
    title: "Hematyu",
    description: "Personal finance ecosystem featuring 'AI Roast' financial analyzer, automatic expense tracking via WhatsApp, and OCR receipt scanning for seamless money management.",
    startDate: "Feb 2024",
    endDate: "Present",
    tags: ["Next.js", "Tailwind CSS", "AI", "WhatsApp API", "OCR"],
    imageUrl: "/projects/hematyu.png",
    images: ["/projects/hematyu.png"],
    href: "http://hematyu.com/",
  },
  {
    project_id: "numpux",
    title: "Numpux",
    description: "A minimalist task management platform designed for deep work. Integrates Kanban workflows and calendar planning into a cohesive productivity experience.",
    startDate: "Jan 2024",
    endDate: "Feb 2024",
    tags: ["Next.js", "Tailwind CSS", "Vercel", "Task Management"],
    imageUrl: "/projects/numpux.png",
    images: ["/projects/numpux.png"],
    href: "https://numpux.vercel.app/",
    githubUrl: "https://github.com/sepsu-dev/numpux",
  },
  {
    project_id: "naha-admin",
    title: "Naha Admin",
    description: "Modern, clean-coded administrative dashboard template. Engineered with Bootstrap 5 and Vanilla JS for high performance and lightweight integration.",
    startDate: "Nov 2023",
    endDate: "Dec 2023",
    tags: ["HTML5", "CSS3", "Bootstrap 5", "JavaScript"],
    imageUrl: "/projects/naha-admin.png",
    images: ["/projects/naha-admin.png"],
    href: "https://naha-admin.vercel.app/index",
    githubUrl: "https://github.com/sepsu-dev/naha-admin",
  },
  {
    project_id: "cek-bmi-yu",
    title: "Cek BMI Yu",
    description: "High-fidelity health utility for real-time BMI calculations. Features interactive dynamic sliders and instant healthy weight classification insights.",
    startDate: "Oct 2023",
    endDate: "Oct 2023",
    tags: ["React", "Tailwind CSS", "Vercel", "UI/UX"],
    imageUrl: "/projects/cek-bmi-yu.png",
    images: ["/projects/cek-bmi-yu.png"],
    href: "https://cek-bmi-yu.vercel.app/",
    githubUrl: "https://github.com/sepsu-dev/cek-bmi-yu",
  },
  {
    project_id: "sepsu-dev",
    title: "sepsu.dev",
    description: "My personal portfolio website designed with a premium, technical aesthetic. Built with Next.js 15 and Tailwind CSS to showcase engineering work and experience.",
    startDate: "May 2024",
    endDate: "Present",
    tags: ["Next.js 15", "React", "Tailwind CSS", "Framer Motion"],
    imageUrl: "/projects/sepsu-dev.png",
    images: ["/projects/sepsu-dev.png"],
    href: "https://sepsu.dev",
    githubUrl: "https://github.com/sepsu-dev/sepsu-dev",
  },
];